services:
    app:
        image: "ravuthz/laravel-php"
        container_name: app
        restart: always
        env_file:
            - ./docker/.env
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
            # DB_CONNECTION: pgsql
            # DB_HOST: db-pgsql
            # DB_PORT: 5432
            DB_CONNECTION: mysql
            DB_HOST: db-mysql
            DB_PORT: 3306
        depends_on:
            - db-pgsql
            - db-mysql
        volumes:
            - ./docker/php/:/usr/local/etc/php/conf.d/
            - ./docker/logs/php/:/var/log/fpm-php.www.log/
            - ./:/var/www/
        networks:
            - laravel-network

    web:
        image: "nginx:alpine"
        container_name: web
        restart: unless-stopped
        tty: true
        ports:
            - "9090:80"
            - "9443:443"
        depends_on:
            - app
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d/
            - ./docker/logs/nginx/:/var/log/nginx/
            - ./:/var/www/
        networks:
            - laravel-network

    db-pgsql:
        image: "postgres:alpine"
        container_name: db-pgsql
        restart: always
        tty: true
        ports:
            - "5439:5432"
        env_file:
            - ./docker/.env
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: db-pgsql
        volumes:
            - db_pgsql:/var/lib/postgresql/
        networks:
            - laravel-network

    db-mysql:
        image: "mysql:latest"
        container_name: db-mysql
        restart: always
        tty: true
        ports:
            - "3399:3306"
        env_file:
            - ./docker/.env
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: db-mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
            interval: 3s
            retries: 3
            start_period: 30s
        volumes:
            - db_mysql:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - laravel-network

    adminer:
        image: "adminer:latest"
        ports:
            - 9191:8080
        networks:
            - laravel-network

volumes:
    db_pgsql:
        driver: local
    db_mysql:
        driver: local

networks:
    laravel-network:
        driver: bridge
        external: false
